name: CI/CD Deploy

on:
  push:
    branches:
      - master  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repo
        uses: actions/checkout@v3

      # Build Docker images
      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/blog-backend:latest ./backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/blog-frontend:latest ./frontend

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push images to Docker Hub
      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/blog-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/blog-frontend:latest

      # Deploy on server via password-based SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
         script: |
            docker network create blog-net || true
            docker-compose -f /root/DOCKER_DEPLOY/docker-compose.yml pull
            docker-compose -f /root/DOCKER_DEPLOY/docker-compose.yml up -d
